Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/09/2024
Var
null1,null2:inteiro
null3:real

Inicio
escreval("Numero Total de Pessoas em um metro quadrado?")
leia(null1)
escreval("o tamanho da area onde esta os participante?")
leia(null2)
null3<- (null1 * null2)/1
escreval("o número total de participantes e ",null3)
Fimalgoritmo