Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/09/2024
Var
    matr,senh:inteiro
    valide1:logico
Inicio
escreval("sua matricula")
leia(matr)
escreval("sua senha")
leia(senh)
valide1<- (( matr = 987) E (senh = 789 )) ou (( matr = 321) E (senh = 123 )) ou (( matr = 654) E (senh = 456 ))
escreval("voce tem acesso", valide1)


Fimalgoritmo